#!/bin/sh
# tuptime - Report the historical and statistical running time of the system, keeping it between restarts.
# Author Ricardo F. - 2015

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

### BEGIN INIT INFO
# Provides:          tuptime
# Required-Start:    $local_fs $time $remote_fs
# Required-Stop:     $local_fs $time $remote_fs
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start tuptime at boot time
# Description:       Update tuptime.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
. /lib/init/vars.sh
. /lib/lsb/init-functions

NAME='tuptime'
DAEMON="/usr/bin/$NAME"


do_start () {
        # Start service
        log_action_begin_msg "Starting $NAME"
        log_end_msg 0
        $DAEMON -x > /dev/null
}

do_stop () {
        # Stop service
        log_action_begin_msg "Stopping $NAME"
        log_end_msg 0
        $DAEMON -xg > /dev/null
}

do_status () {
	# Status service
	$DAEMON
}


case "$1" in
  start|"")
        do_start
        ;;
  restart|force-reload)
        log_action_begin_msg "Restarting $NAME"
        log_end_msg 0
        do_stop
        do_start
        ;;
  stop)
        do_stop
        ;;
  status)
        do_status
        exit $?
        ;;
  *)
        echo "Usage: $NAME [start|stop|restart|status]" >&2
        exit 3
        ;;
esac

