#!/bin/sh
#
# $OpenBSD$

daemon="/usr/local/bin/tuptime"
daemon_flags="-x"

rc_reload=NO
rc_stop=NO
rc_check=NO

. /etc/rc.d/rc.subr

rc_cmd $1

# Enable:
# echo 'rc_scripts="tuptime"' >> /etc/rc.conf.local 

# Execution at shutdown:
# echo '/usr/local/bin/python3 /usr/local/bin/tuptime -xg' >>
# /etc/rc.shutdown
