#!/usr/bin/env python
# -*- coding: utf-8 -*-

# tuptime - Report the historical and statistical running time of the system, keeping it between restarts.
# Copyright (C) 2011-2015 - Ricardo F.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

try:
    import sys, os, optparse, sqlite3, locale, platform
    from datetime import datetime
except Exception as e:
    sys.exit('ERROR modules are not imported correctly: ' + str(e))

version = '2.6.10'
def_db_file = '/var/lib/tuptime/tuptime.db'
def_seconds = False
locale.setlocale(locale.LC_ALL, '')
def_date_format = '%X %x'
dec = int(2)  # Decimals for printed values


def vprint(*args):
    """Print verbose information"""
    if opt.verbose:
        for arg in args:
            sys.stdout.write(str(arg))
        print('')


def time_conv(secs):
    """Convert seconds to human readable syle"""
    try:
        if secs == 0:
            return '0 seconds'

        tm = {'years': int(0), 'days': int(0), 'hours': int(0), 'minutes': int(0), 'seconds': int(0)}
        tm_tuple = ('years', 'days', 'hours', 'minutes', 'seconds')
        zero_enter = True
        human_tm = ''

        # Get times values
        tm['minutes'], tm['seconds'] = divmod(secs, 60)
        tm['hours'], tm['minutes'] = divmod(tm['minutes'], 60)
        tm['days'], tm['hours'] = divmod(tm['hours'], 24)
        tm['years'], tm['days'] = divmod(tm['days'], 365)

        for key in tm_tuple:  # avoid print empty values at the beginning
            if tm[key] == 0 and zero_enter:
                continue
            else:
                human_tm += str(int(tm[key]))+' '+str(key) + ', '
                zero_enter = False

        if human_tm.find('minutes, '):  # nice sentence end, remove comma
            human_tm = human_tm.replace('minutes, ', 'minutes and ')

        return str(human_tm[:-2])  # return without last comma and space chareacter
    except Exception as e:
        sys.exit('ERROR converting seconds: '+ str(e))


def main():
    global opt

    # - Reading command line parameters
    parser = optparse.OptionParser()
    parser.add_option('-d', '--date',
        dest='date_format',
        default=def_date_format,
        action='store',
        help='date format')
    parser.add_option('-e', '--enumerate',
        dest='enum',
        default=False,
        action='store_true',
        help='enumerate system life')
    parser.add_option('-f', '--filedb',
        dest='db_file',
        default=def_db_file,
        action='store',
        help='database file',
        metavar='FILE')
    parser.add_option('-g', '--graceful',
        dest='shutdown',
        action='store_const',
        default='0',
        const='1',
        help='gracefully shutdown')
    parser.add_option('-s', '--seconds',
        dest='seconds',
        default=def_seconds,
        action='store_true',
        help='output time in seconds and epoch')
    parser.add_option('-x', '--silent',
        dest='silent',
        default=False,
        action='store_true',
        help='update values without print')
    parser.add_option('-v', '--verbose',
        dest='verbose',
        default=False,
        action='store_true',
        help='verbose output')
    parser.add_option('-V', '--version',
        dest='version',
        default=False,
        action='store_true',
        help='show version')
    opt, _ = parser.parse_args()

    # - Parse version option
    if opt.version:
        print ('tuptime version ' + version)
        sys.exit(0)

    # - Swich for running in FreeBSD (with linprocfs) or Linux
    if (platform.system() == "FreeBSD"):
        procfs = "/compat/linux/proc"
    else:
        procfs = "/proc"

    # - Reading /proc/uptime
    try:
        with open(procfs + '/uptime') as fl:
            uptime = float(fl.readline().split()[0])
            vprint(procfs + '/uptime = ' + str(uptime))
    except Exception as e:
        sys.exit('ERROR reading ' + procfs + '/uptime'+ str(e))

    # - Reading btime from /proc/stat
    try:
        with open(procfs + '/stat') as fl:
            for line in fl:
                if line.startswith('btime'):
                    btime = int(line.split()[1])
            vprint(procfs + '/stat btime = ' + str(btime))
    except Exception as e:
        sys.exit('ERROR reading ' + procfs + '/stat'+ str(e))

    # - Assure state of db file
    try:
        if os.path.isdir(os.path.dirname(opt.db_file)):
            vprint('Directory exists = ', os.path.dirname(opt.db_file))
        else:
            vprint('Creating directory = ', opt.db_file)
            os.makedirs(os.path.dirname(opt.db_file))

        if os.path.isfile(opt.db_file):
            vprint('DB file exists = ', opt.db_file)
        else:
            vprint('Creating DB file = ', opt.db_file)
            db = sqlite3.connect(opt.db_file)
            conn = db.cursor()
            conn.execute('create table if not exists tuptime(uptime real, btime integer, shutdown integer, downtime real)')
            conn.execute('insert into tuptime values (?,?,?,?)', (str(uptime), str(btime), str(opt.shutdown), str('-1')))
            db.commit()
            db.close()
    except Exception as e:
        sys.exit('ERROR creating db file: '+ str(e))

    # - Creating db connection
    try:
        db = sqlite3.connect(opt.db_file)
        conn = db.cursor()
    except Exception as e:
        sys.exit('ERROR connecting db: '+ str(e))

    # - Reading last btime for db
    try:
        conn.execute('select btime from tuptime where oid = (select max(oid) from tuptime)')
        last_btime = int(conn.fetchone()[0])
        vprint('Last btime from db = ', last_btime)
    except Exception as e:
        sys.exit('ERROR reading from db: '+ str(e))


    # - Test if system was resterted
    # How tuptime do it:
    #    Checking if last_btime saved into db plus uptime is lower than actual btime
    #
    # In some particular cases the btime value from /proc/stat may change. Testing only last_btime vs
    # actual btime can produce a false shutdown register.
    # Usually happend on virtualized enviroments, servers with high load or when ntp are running.
    # Related to kernel system clock frequency, computation of jiffies / HZ and the problem of lost ticks.
    # More info in Debian bug 119971 and rfc1589

    try:
        if (last_btime + uptime) < btime:
            vprint('System was restarted')
            # - Reading last uptime for db
            conn.execute('select uptime from tuptime where oid = (select max(oid) from tuptime)')
            last_uptime = int(conn.fetchone()[0])
            vprint('Last uptime from db = ', last_uptime)

            conn.execute('update tuptime set downtime = '+ str(btime - (last_uptime + last_btime)) +' where oid = (select max(oid) from tuptime)')  # Save downtime for previous boot
            conn.execute('insert into tuptime values (?,?,?,?)', (str(uptime), str(btime), str(opt.shutdown), str('-1')))
            last_btime = btime
        else:
            vprint('System wasn\'t restarted. Updating db values...')
            conn.execute('update tuptime set uptime = '+ str(uptime) +', shutdown = '+ str(opt.shutdown) +' where oid = (select max(oid) from tuptime)')
    except Exception as e:
        if type(e).__name__ == 'OperationalError':
            vprint('WARNING values not saved into db - Test file permissions')
        if (last_btime + uptime) < btime:
            # If you see this error, maybe systemd script isn't executed at startup
            # or the db file (def_db_file) have wrong permissions.
            sys.exit('ERROR After system restart, the values must be saved into db. Please, execute tuptime with a privileged user.')
            vprint('WARNING', e)
    # - Get number of startups
    conn.execute('select max(oid) from tuptime')
    startups = int(conn.fetchone()[0])

    # - Get first btime
    conn.execute('select btime from tuptime limit 1')
    first_btime = int(conn.fetchone()[0])

    # - Get total uptime
    # conn.execute('select sum(uptime) from tuptime')
    # hack for allow unprivileged users that can not update database show results
    conn.execute('select sum(uptime) from tuptime where oid < (select max(oid) from tuptime)')
    total_uptime = sum(filter(None, [conn.fetchone()[0], uptime]))

    # - Get bad shutdowns
    conn.execute('select count(shutdown) from tuptime where shutdown = 0 and oid < (select max(oid) from tuptime)')
    bad_shdown = int(conn.fetchone()[0])
    # conn.execute('select count(shutdown) from tuptime where shutdown = 1 and oid < (select max(oid) from tuptime)')
    # ok_shdown = int(conn.fetchone()[0])
    # hack for avoid one query to the db
    ok_shdown = startups - bad_shdown - 1

    # - Get life time
    conn.execute('select btime from tuptime where oid = (select min(oid) from tuptime)')
    first_btime = int(conn.fetchone()[0])
    sys_life = (last_btime + uptime) - first_btime

    # - Print each row registered in db
    if opt.enum:
        keys = ('uptime', 'boot_time', 'pwoff_status', 'downtime')
        for row_num in range(1, (startups + 1)):
            conn.execute('select * from tuptime where oid = '+ str(row_num))
            values = list(conn.fetchone())
            vprint('Fetched row '+ str(row_num) +' with '+ str(values))
            row_dict = dict(zip(keys, values))  # join key + value for db row
            if row_dict['pwoff_status'] == 1:
                e_pwoff = 'OK'
            else:
                e_pwoff = 'BAD'

            e_btime = row_dict['boot_time']
            e_btime_h = str(datetime.fromtimestamp(e_btime).strftime(opt.date_format))
            e_shutdown = row_dict['boot_time'] + row_dict['uptime']
            e_shutdown_h = str(datetime.fromtimestamp(e_shutdown).strftime(opt.date_format))

            if row_num > 1:  # first row don't have previous values
                e_last_shutdown = last_row_dict['boot_time'] + last_row_dict['uptime']
                e_downtime = row_dict['boot_time'] - e_last_shutdown
                e_downtime_h = time_conv(e_downtime)
                if opt.seconds:
                    print('Downtime: ' + str(round(e_downtime, dec)))
                else:
                    print('Downtime: ' + e_downtime_h)
                print('')

            if opt.seconds:
                print('Startup:  ' + str(row_num) + '  at  '+ str(e_btime))
                if not row_num == startups:
                    print('Uptime:   ' + str(round(row_dict['uptime'], dec)))
                    print('Shutdown: ' + str(e_pwoff) + '  at  '+ str(e_shutdown))
                else:
                    print('Uptime:   ' + str(round(uptime, dec)))
            else:
                print('Startup:  ' + str(row_num) + '  at  '+ e_btime_h)
                if not row_num == startups:
                    print('Uptime:   ' + time_conv(row_dict['uptime']))
                    print('Shutdown: ' + str(e_pwoff) + '  at  '+ e_shutdown_h)
                else:
                    print('Uptime:   ' + time_conv(uptime))
            print('')
            last_row_dict = row_dict
    
    # - Print each row registered in db
    if opt.enum:
        keys = ('uptime', 'boot_time', 'pwoff_status', 'downtime')
        for row_num in range(1, (startups + 1)):
            conn.execute('select * from tuptime where oid = '+ str(row_num))
            values = list(conn.fetchone())
            vprint('Fetched row '+ str(row_num) +' with '+ str(values))
            row_dict = dict(zip(keys, values))  # join key + value for db row
            if row_dict['pwoff_status'] == 1:
                e_pwoff = 'OK'
            else:
                e_pwoff = 'BAD'

            e_btime = row_dict['boot_time']
            e_btime_h = str(datetime.fromtimestamp(e_btime).strftime(opt.date_format))
            e_shutdown = row_dict['boot_time'] + row_dict['uptime']
            e_shutdown_h = str(datetime.fromtimestamp(e_shutdown).strftime(opt.date_format))

            if opt.seconds:
                print('Startup:  ' + str(row_num) + '  at  '+ str(e_btime))
                if not row_num == startups:  # For avoid last shutdown and hack for unprivileged users
                    print('Uptime:   ' + str(round(row_dict['uptime'], dec)))
                    print('Shutdown: ' + str(e_pwoff) + '  at  '+ str(e_shutdown))
                else:
                    print('Uptime:   ' + str(round(uptime, dec)))
            else:
                print('Startup:  ' + str(row_num) + '  at  '+ e_btime_h)
                if not row_num == startups:  # For avoid last shutdown and hack for unprivileged users
                    print('Uptime:   ' + time_conv(row_dict['uptime']))
                    print('Shutdown: ' + str(e_pwoff) + '  at  '+ e_shutdown_h)
                else:
                    print('Uptime:   ' + time_conv(uptime))
            print('')
            e_downtime = row_dict['downtime']
	    if e_downtime >= 0:   # Avoid first -1 register
                e_downtime_h = time_conv(e_downtime)
                if opt.seconds:
                    print('Downtime: ' + str(round(e_downtime, dec)))
                else:
                    print('Downtime: ' + e_downtime_h)
                print('')
    # Large uptime
    # hack for allow unprivileged users that can not update database show results
    conn.execute('select max(uptime), btime, oid from tuptime where oid < (select max(oid) from tuptime)')
    large_uptime_time_db, large_uptime_date_db, large_uptime_row = conn.fetchone()
    if large_uptime_time_db > uptime:
        large_uptime_time = large_uptime_time_db
        large_uptime_date = large_uptime_date_db
    else:
        large_uptime_time = uptime
        large_uptime_date = last_btime
        large_uptime_row += 1

    # Short uptime
    # hack for allow unprivileged users that can not update database show results
    conn.execute('select min(uptime), btime, oid from tuptime where oid < (select max(oid) from tuptime)')
    short_uptime_time_db, short_uptime_date_db, short_uptime_row = conn.fetchone()
    if short_uptime_time_db < uptime:
        short_uptime_time = short_uptime_time_db
        short_uptime_date = short_uptime_date_db
    else:
        short_uptime_time = uptime
        short_uptime_date = last_btime
        short_uptime_row += 1
     
    # Large dowtime
    # hack for allow unprivileged users that can not update database show results
    conn.execute('select max(downtime), btime, oid, uptime from tuptime where oid < (select max(oid) from tuptime)')
    large_downtime_time, large_downtime_date_db, large_downtime_row, large_uptime_db = conn.fetchone()
    large_downtime_date = large_downtime_date_db + large_uptime_db

    # short dowtime
    # hack for allow unprivileged users that can not update database show results
    conn.execute('select min(downtime), btime, oid, uptime from tuptime where oid < (select max(oid) from tuptime)')
    short_downtime_time, short_downtime_date_db, short_downtime_row, short_uptime_db = conn.fetchone()
    short_downtime_date = short_downtime_date_db + short_uptime_db

    if opt.seconds:
        print('Large uptime:\t\t[' + str(large_uptime_row) +'] '+ str(large_uptime_time) + '   started at   ' + str(large_uptime_date))    
        print('Large downtime:\t\t[' + str(large_downtime_row) +'] '+ str(large_downtime_time) + '   started at   ' + str(large_downtime_date))    
        print('Short uptime:\t\t[' + str(short_uptime_row) +'] '+ str(short_uptime_time) + '   started at   ' + str(short_uptime_date))    
        print('Short downtime:\t\t[' + str(short_downtime_row) +'] '+ str(short_downtime_time) + '   started at   ' + str(short_downtime_date))    
    else:
        large_uptime_date_h = str(datetime.fromtimestamp(large_uptime_date).strftime(opt.date_format))
        large_downtime_date_h = str(datetime.fromtimestamp(large_downtime_date).strftime(opt.date_format))
        short_uptime_date_h = str(datetime.fromtimestamp(short_uptime_date).strftime(opt.date_format))
        short_downtime_date_h = str(datetime.fromtimestamp(short_downtime_date).strftime(opt.date_format))
        large_uptime_time_h =  time_conv(large_uptime_time)
        large_downtime_time_h = time_conv(large_downtime_time)
        short_uptime_time_h = time_conv(short_uptime_time)
        short_downtime_time_h = time_conv(short_downtime_time)
        
        print('Large uptime:\t\t[' + str(large_uptime_row) +'] '+ str(large_uptime_time_h) + '   started at   ' + str(large_uptime_date_h))    
        print('Large downtime:\t\t[' + str(large_downtime_row) +'] '+ str(large_downtime_time_h) + '   started at   ' + str(large_downtime_date_h))    
        print('Short uptime:\t\t[' + str(short_uptime_row) +'] '+ str(short_uptime_time_h) + '   started at   ' + str(short_uptime_date_h))    
        print('Short downtime:\t\t[' + str(short_downtime_row) +'] '+ str(short_downtime_time_h) + '   started at   ' + str(short_downtime_date_h))    

    print('')

    # - Closing db connection
    try:
        db.commit()
        db.close()
    except Exception as e:
        sys.exit('ERROR closing db connection: '+ str(e))

    if opt.silent:
        vprint('Only update')
    else:
        # - Get average uptime and uptime rate
        average = float(total_uptime / startups)
        uprate = float((total_uptime * 100 ) / (sys_life))
        if startups == 1:
            total_downtime = 0
        else:
            total_downtime = float(sys_life - total_uptime)
        downrate = abs(float((total_downtime * 100 ) / (sys_life)))
        average_down = float(total_downtime / startups)

        vprint('')

        if opt.seconds:
            print('System startups:\t' + str(startups) + '   since   ' + str(first_btime))
            print('System shutdowns:\t' + str(ok_shdown) + ' ok   -   ' + str(bad_shdown) + ' bad')
            print('Average uptime: \t' + str(round(average, dec)))
            print('Average downtime: \t' + str(round(average_down, dec)))
            print('Current uptime: \t' + str(uptime) + '   since   ' + str(last_btime))
            print('Uptime rate: \t\t' + str(round(uprate, dec)) + ' %')
            print('Downtime rate: \t\t' + str(round(downrate, dec)) + ' %')
            print('System uptime: \t\t' + str(round(total_uptime, dec)))
            print('System downtime: \t' + str(round(total_downtime, dec)))
            print('System life: \t\t' + str(round(sys_life, dec)))
        else:
            # - Get some values in human readable style
            first_btime_h = str(datetime.fromtimestamp(first_btime).strftime(opt.date_format))
            last_btime_h = str(datetime.fromtimestamp(last_btime).strftime(opt.date_format))
            average_h = str(time_conv(total_uptime / startups))
            average_down_h = str(time_conv(total_downtime / startups))

            print('System startups:\t' + str(startups) + '   since   ' + first_btime_h)
            print('System shutdowns:\t' + str(ok_shdown) + ' ok   -   ' + str(bad_shdown) + ' bad')
            print('Average uptime: \t' + average_h)
            print('Average downtime: \t' + average_down_h)
            print('Current uptime: \t' + time_conv(uptime) + '   since   ' + last_btime_h)
            print('Uptime rate: \t\t' + str(round(uprate, dec)) + ' %')
            print('Downtime rate: \t\t' + str(round(downrate, dec)) + ' %')
            print('System uptime: \t\t' + time_conv(total_uptime))
            print('System downtime: \t' + time_conv(total_downtime))
            print('System life: \t\t' + time_conv(sys_life))

if __name__ == "__main__":
    main()
