'\" t
.TH TUPTIME 1 "Jan 2024" "5.2.4" "General Commands Manual"

.SH NAME
tuptime \- Report historical and statistical real time of the system, preserving it between restarts. Total uptime.

.SH SYNOPSIS
tuptime [\-h] [\-A STARTUP] [\-b] [\-c] [\-d DATETIME_FMT] [\-e DECIMALS] [\-E STARTUP] [\-f FILE] [\-g] [\-i] [\-k] [\-l] [\-n] [\-o TYPE] [\-p] [\-q] [\-r] [\-s] [\-S STARTUP] [\-t] [\-\-tat TIMESTAMP] [\-\-tsince TIMESTAMP] [\-\-tuntil TIMESTAMP] [\-U STARTUP] [\-v] [\-V]

.SH DESCRIPTION
.RS
.RE
Tuptime reports historical and statistical real time of 
the system, preserving it between restarts. Indeed, it can:
.RS
- Count system startups
.RS
.RE
- Register first boot time (a.k.a. installation time)
.RS
.RE
- Count nicely and accidentally shutdowns
.RS
.RE
- Uptime and downtime percentage since first boot time
.RS
.RE
- Accumulated system uptime (running and sleeping), downtime and total
.RS
.RE
- Register used kernels and boot IDs
.RS
.RE
- Report current uptime
.RS
.RE
- Print formatted table or list with the system history
.RS
.RE
- Narrow reports since, until or at a given startup or timestamp
.RS
.RE
- Output in csv format

.SH OPTIONS
.SS ARGUMENTS
.TS
tab (@);
l lx.
\-h | \-\-help@T{
Show this help message and exit
T}
\-A | \-\-at STARTUP@T{
Limit to this startup number
T}
\-b | \-\-bootid@T{
Show boot identifier
T}
\-c | \-\-csv@T{
Output in csv format
T}
\-d | \-\-date DATETIME_FMT@T{
Datetime/timestamp format output
T}
\-e | \-\-dec DECIMALS@T{
Number of decimals in percentages
T}
\-E | \-\-exclude STARTUP@T{
Startup numbers to exclude
T}
\-f | \-\-file FILE@T{
Database file (file path)
T}
\-g | \-\-graceful@T{
Register a graceful shutdown
T}
\-i | \-\-invert@T{
Startup number in reverse count | swich between longest/shortest on default output
T}
\-k | \-\-kernel@T{
Show kernel version
T}
\-l | \-\-list@T{
Enumerate system life as list
T}
\-n | \-\-noup@T{
Avoid update values into DB
T}
\-o | \-\-order TYPE@T{
Order enumerate by [u|r|s|e|d|k] (u = uptime | r = runtime | s = sleep time | e = end status | d = downtime | k = kernel)
T}
\-p | \-\-power@T{
Show power states run + sleep
T}
\-q | \-\-quiet@T{
Update values into DB without output
T}
\-r | \-\-reverse@T{
Reverse order in listings
T}
\-s | \-\-seconds@T{
Output time in seconds and epoch
T}
\-S | \-\-since STARTUP@T{
Limit from this startup number
T}
\-t | \-\-table@T{
Enumerate system life as table
T}
\-\-tat TIMESTAMP@T{
Report system status at specific timestamp
T}
\-\-tsince TIMESTAMP@T{
Limit from this epoch timestamp
T}
\-\-tuntil TIMESTAMP@T{
Limit until this epoch timestamp
T}
\-U | \-\-until STARTUP@T{
Limit up until this startup number
T}
\-v | \-\-verbose@T{
Verbose output
T}
\-V | \-\-version@T{
Show version
T}
.TE
.SS ENVIRONMENT
.RE
TUPTIME_DBF
.RS
Set an alternative database file path. The argument -f, --filedb takes
precedence over this.
.TE

.SH DEFAULT OUTPUT
.RS
.RE
System startups:
.RS
Total number of system startups from since first timestamp available.

.RE
System shutdowns:
.RS
Total number of shutdowns done correctly or incorrectly.

.RE
System life:
.RS
Time counter since first startup timestamp available.

.RE
System uptime:
.RE
System downtime:
.RS
Percentage of time and time counter.

.RE
Longest uptime:
.RE
Longest downtime:
.RS
Time counter and date with the complete longest uptime/downtime register.

.RE
Average uptime:
.RE
Average downtime:
.RS
Average time counter.

.RE
Current uptime:
.RS
Actual time counter and datetime since registered boot timestamp.

.SH EXAMPLES
.TP 
.BI tuptime
Default output.
.TP 
.B tuptime -t
Enumerate system life as table.
.TP 
.B tuptime -l
Enumerate system life as list.
.TP
.B tuptime -k 
Add kernel information to the output.
.TP
.B tuptime --csv
Report in csv format.
.TP
.B tuptime -s
Change default human readable datetime/timestamp style and print times in
seconds and datetimes in epoch.
.TP
.B tuptime -d '%H:%M:%S   %m-%d-%Y'
Change the datetime/timestamp format. By default the output use the
configured system locales.
.TP
.B tuptime --tsince -31557600
Report since one year ago.

.SH FILES
.TP
.I /etc/cron.d/tuptime
Scheduled cron file.
.TP
.I /etc/init.d/tuptime
Init file.
.TP
.I /lib/systemd/system/tuptime.service
Systemd service unit file. Register time values into database.
.TP
.I /usr/bin/tuptime
Main and only executable file.
.TP
.I /usr/share/doc/tuptime/
Directory with multiple documentation files.
.TP
.I /lib/systemd/system/tuptime-sync.timer
Systemd .timer unit for use instead of cron. Only executes tuptime-sync.service.
.TP
.I /lib/systemd/system/tuptime-sync.service
Systemd .service unit required by tuptime-sync.timer. Updates time values into database.
.TP
.I /usr/share/man/man1/tuptime.1
Manual page.

.SH SEE ALSO
.TP
.I /usr/share/doc/tuptime/tuptime-manual.txt.gz
Detailed documentation.
.TP
.I https://github.com/rfmoz/tuptime/
Official repository.

.SH "AUTHOR"
.PP
Ricardo Fraile <r@rfmoz.eu>

.SH "COPYRIGHT"
.PP
Copyright (C) 2024 by Ricardo F. All Rights Reserved.

This product is distributed in the hope that it will be useful, but
WITHOUT any warranty; without even the implied warranty of 
MERCHANTABILITY or FITNESS for a particular purpose.
