#!/bin/sh
#
# PROVIDE: tuptime
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="tuptime"
rcvar=tuptime_enable

start_cmd="${name}_start"
stop_cmd="${name}_stop"

tuptime_start()
{
	command_args="-x"

	$name $command_args
}

tuptime_stop()
{
	command_args="-xg"

	$name $command_args
}

load_rc_config $name
run_rc_command "$1"
