#!/bin/sh /etc/rc.common

START=99
STOP=60

start() {
        echo 'Tuptime start'
        if [ ! -e /var/lib/tuptime ]; then
           ln -s /opt/tuptime/ /var/lib/tuptime
        fi
        /usr/bin/python3 /usr/bin/tuptime -q
}

stop() {
        echo 'Tuptime stop'
        /usr/bin/python3 /usr/bin/tuptime -qg
}
