#!/bin/sh
#
# PROVIDE: tuptime
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="tuptime"
user="tuptime"
rcvar=tuptime_enable

start_cmd="${name}_start"
stop_cmd="${name}_stop"

export PATH=$PATH:/usr/local/bin/

tuptime_start()
{
	command_args="-x"

	su -m $user -c "$name $command_args"
}

tuptime_stop()
{
	command_args="-xg"

	su -m $user -c "$name $command_args"
}

load_rc_config $name
run_rc_command "$1"
